language: clojure

install: true

before_script:
- curl -O https://download.clojure.org/install/linux-install-1.9.0.394.sh
- chmod +x linux-install-1.9.0.394.sh
- sudo ./linux-install-1.9.0.394.sh
- sudo apt-get update -qq
- sudo apt-get install -qq --yes rlwrap

script: make test
